### ISSUE TITLE
media upload issue

### ISSUE THREAD

**Issue by benjaminaaron** [FuturICT2/FIN4Xplorer#14]
This issue is just to upload media files to then be linked into the Readme.

**Comment by benjaminaaron** [comment]
![ActionTypeCreationClaim](https://user-images.githubusercontent.com/5141792/61829156-9f107b00-ae68-11e9-8ab7-6800f249caf8.png)

**Comment by benjaminaaron** [comment]
![Rewards](https://user-images.githubusercontent.com/5141792/61829167-a3d52f00-ae68-11e9-98ef-76878f39d2d8.png)

**Comment by simonzachau** [comment]
![Screen_Shot_2019-07-28_at_23_22_09](https://user-images.githubusercontent.com/9423641/62013340-4f47f180-b191-11e9-8e9f-fa45b0577063.png)

**Comment by benjaminaaron** [comment]
![eth_fremdmedien_logo_COSS1-768x140](https://user-images.githubusercontent.com/5141792/72538450-25d56c00-387e-11ea-84bd-18aa61993cc6.png)
